# Generated by Django 4.0.4 on 2022-04-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='member',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='is an adult'),
        ),
    ]
