# Generated by Django 4.0.4 on 2022-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_is_parent_member_is_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='panic_flag',
            field=models.BooleanField(default=False, verbose_name='panic switch'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
