# Generated by Django 4.0.4 on 2022-04-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_panic_flag_alter_member_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
